-- KMO catalog products seed
--
-- IMPORTANT:
-- - Run this after supabase-hr/products_setup.sql.
-- - Run this against the HR Supabase project only: ybyseaenceyswjnwdmdf.
-- - Generated from D:/AI-Workspace/projects/kmo-landing-page/assets/product_catalog_template.csv.

insert into public.products (
  id, brand, model, name, price, category, description, image_url,
  shopee_url, allow_booking, allow_order, featured
) values
  ('kmo-001', 'Africa Twin 2020', '', 'แคสบาร์ล่าง+แล็คใส่ปี๊ป', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Africa Twin 2020 รายการ: แคสบาร์ล่าง+แล็คใส่ปี๊ป', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-002', 'Aprilia', 'Sr gt200', 'เสริมความแข็งแรงแร็คท้ายเพื่อรับน้ำหนัก และแรงกระแทก', 0, 'rear', 'งานคัสตอม KMO สำหรับ Aprilia Sr gt200 รายการ: เสริมความแข็งแรงแร็คท้ายเพื่อรับน้ำหนัก และแรงกระแทก', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-003', 'Aprilia', 'SRGT200', 'แคสบาร์', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Aprilia SRGT200 รายการ: แคสบาร์', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-004', 'BAJAJ', 'Dominar400', 'แร็คท้าย', 0, 'rear', 'งานคัสตอม KMO สำหรับ BAJAJ Dominar400 รายการ: แร็คท้าย', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-005', 'Bajaj', 'Dominar400 touring', 'แร็คท้าย + แร็คข้าง', 0, 'side', 'งานคัสตอม KMO สำหรับ Bajaj Dominar400 touring รายการ: แร็คท้าย + แร็คข้าง', 'assets/images/rack-side.jpg', '', true, true, false),
  ('kmo-006', 'Bajaj Dominar 400', '', 'แร็คท้ายสีดำ', 0, 'rear', 'งานคัสตอม KMO สำหรับ Bajaj Dominar 400 รายการ: แร็คท้ายสีดำ', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-007', 'benelli', 'tnt300', 'แร็คท้าย แข็งแรง แบบ 40 กิโล ทุกวัน ขอมีมือจับด้วย', 0, 'rear', 'งานคัสตอม KMO สำหรับ benelli tnt300 รายการ: แร็คท้าย แข็งแรง แบบ 40 กิโล ทุกวัน ขอมีมือจับด้วย', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-008', 'BMW', 'F700GS 2013', 'แคชบาร์', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ BMW F700GS 2013 รายการ: แคชบาร์', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-009', 'BMW', 'F900', 'แร็คท้าย', 0, 'rear', 'งานคัสตอม KMO สำหรับ BMW F900 รายการ: แร็คท้าย', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-010', 'BMW', 'F900xr', 'แก้ไขแร็คข้าง ทรงshad 3p', 0, 'side', 'งานคัสตอม KMO สำหรับ BMW F900xr รายการ: แก้ไขแร็คข้าง ทรงshad 3p', 'assets/images/rack-side.jpg', '', true, true, false),
  ('kmo-011', 'BMW', 'K1300s', 'แร็คข้าง', 0, 'side', 'งานคัสตอม KMO สำหรับ BMW K1300s รายการ: แร็คข้าง', 'assets/images/rack-side.jpg', '', true, true, false),
  ('kmo-012', 'bmw r12 ninet/2024', '', 'crash bar / สีแดง', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ bmw r12 ninet/2024 รายการ: crash bar / สีแดง', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-013', 'BMW R1200GSA 2015', '', 'ซ่อมแร็คปี๊บข้าง และเสริมความแข็งแรงแร็ค', 0, 'side', 'งานคัสตอม KMO สำหรับ BMW R1200GSA 2015 รายการ: ซ่อมแร็คปี๊บข้าง และเสริมความแข็งแรงแร็ค', 'assets/images/rack-side.jpg', '', true, true, false),
  ('kmo-014', 'Cb 150 r 2018', '', 'แร็คท้าย', 0, 'rear', 'งานคัสตอม KMO สำหรับ Cb 150 r 2018 รายการ: แร็คท้าย', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-015', 'Cb150r', '', 'ติดเเคชบาร์รอบคัน และ แร็คท้ายกับแร็คข้าง +ไฟสปอดไลด์ 1ชุดครับ', 0, 'side', 'งานคัสตอม KMO สำหรับ Cb150r รายการ: ติดเเคชบาร์รอบคัน และ แร็คท้ายกับแร็คข้าง +ไฟสปอดไลด์ 1ชุดครับ', 'assets/images/rack-side.jpg', '', true, true, false),
  ('kmo-016', 'CBR 650 r ปี 2023', '', 'แร็คท้าย + แร็คข้าง สี ขอไปเลือกที่ร้านครับ', 0, 'side', 'งานคัสตอม KMO สำหรับ CBR 650 r ปี 2023 รายการ: แร็คท้าย + แร็คข้าง สี ขอไปเลือกที่ร้านครับ', 'assets/images/rack-side.jpg', '', true, true, false),
  ('kmo-017', 'CBR500 / 2020', '', 'แปลง cbr500 เป็นไฟกลม / แปลงขาจับไฟหน้า / จัดสายไฟ', 0, 'accessory', 'งานคัสตอม KMO สำหรับ CBR500 / 2020 รายการ: แปลง cbr500 เป็นไฟกลม / แปลงขาจับไฟหน้า / จัดสายไฟ', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-018', 'CBR500R สีดำ 2024', '', 'แร็คท้าย แร็คข้างซ้าย,ขวา สีดำ ไม่ยื่นออกจากตัวรถมากเกิน', 0, 'side', 'งานคัสตอม KMO สำหรับ CBR500R สีดำ 2024 รายการ: แร็คท้าย แร็คข้างซ้าย,ขวา สีดำ ไม่ยื่นออกจากตัวรถมากเกิน', 'assets/images/rack-side.jpg', '', true, true, false),
  ('kmo-019', 'CLICK125', '', 'แคชบาร์สีดำด้านขึ้นงานกับรถ', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ CLICK125 รายการ: แคชบาร์สีดำด้านขึ้นงานกับรถ', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-020', 'CRF 250 rally 2018', '', 'ทำ cashbar', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ CRF 250 rally 2018 รายการ: ทำ cashbar', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-021', 'Crf250 rally 2017', '', 'แคชบาร์ แร๊คท้าย', 0, 'rear', 'งานคัสตอม KMO สำหรับ Crf250 rally 2017 รายการ: แคชบาร์ แร๊คท้าย', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-022', 'Ducati', 'Hypermotard 950', 'แร็คท้าย', 0, 'rear', 'งานคัสตอม KMO สำหรับ Ducati Hypermotard 950 รายการ: แร็คท้าย', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-023', 'Ducati', 'Muti', 'ซ่อมแคชบาร์', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Ducati Muti รายการ: ซ่อมแคชบาร์', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-024', 'Harley Davidson', '1250 Revolution Max', 'ทำจุดยึดพักเท้าเสริม', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Harley Davidson 1250 Revolution Max รายการ: ทำจุดยึดพักเท้าเสริม', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-025', 'Honda', 'addv3500', '2025', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda addv3500 รายการ: 2025', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-026', 'Honda', 'Adv160', 'ดำ', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Adv160 รายการ: ดำ', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-027', 'Honda', 'Adv350', 'บาร์เสริม ติดตุ๊กตาแฮนด์แบบสั้น', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Adv350 รายการ: บาร์เสริม ติดตุ๊กตาแฮนด์แบบสั้น', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-028', 'Honda', 'Adv350', 'บาร์เสริมติดตุ๊กตาแฮนด์ แบบยาว', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Adv350 รายการ: บาร์เสริมติดตุ๊กตาแฮนด์ แบบยาว', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-029', 'Honda', 'ADV350', 'แคชบาร์ท้าย ADV350', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Honda ADV350 รายการ: แคชบาร์ท้าย ADV350', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-030', 'Honda', 'Africa twin 1000L ตัว 2018 ไตรคัลเลอ', 'แคลชบาร์', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Honda Africa twin 1000L ตัว 2018 ไตรคัลเลอ รายการ: แคลชบาร์', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-031', 'Honda', 'C b 650r', 'แคทบาร์ 1ข้างซ้าย ขอ น็อตใหม่ด้วย', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda C b 650r รายการ: แคทบาร์ 1ข้างซ้าย ขอ น็อตใหม่ด้วย', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-032', 'Honda', 'CB 750 Hornet', 'Crash cage', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Honda CB 750 Hornet รายการ: Crash cage', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-033', 'Honda', 'CB300F', 'แร็คท้ายติดปี๊บ 65 ลิตร +แร็คข้าง กระเป๋า motowolf 30ลิตร', 0, 'side', 'งานคัสตอม KMO สำหรับ Honda CB300F รายการ: แร็คท้ายติดปี๊บ 65 ลิตร +แร็คข้าง กระเป๋า motowolf 30ลิตร', 'assets/images/rack-side.jpg', '', true, true, false),
  ('kmo-034', 'Honda', 'Cb500x', 'ติดตั้ง n1go', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Cb500x รายการ: ติดตั้ง n1go', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-035', 'Honda', 'CB500X 2019', 'ดัดแคชบาร์ด้านขวาให้เท่ากัน, เสริมห่วงใต้รถเพื่อเกี่ยวสปริงขาตั้งคู่', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Honda CB500X 2019 รายการ: ดัดแคชบาร์ด้านขวาให้เท่ากัน, เสริมห่วงใต้รถเพื่อเกี่ยวสปริงขาตั้งคู่', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-036', 'Honda', 'CB750 Hornet', 'Crash bars (for stunt / gymkhana)', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Honda CB750 Hornet รายการ: Crash bars (for stunt / gymkhana)', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-037', 'Honda', 'CBR1000RR-R SP Fireblade', 'แร็คท้าย+ข้าง เคชบาร์ (ถอดประกอบง่าย)', 0, 'rear', 'งานคัสตอม KMO สำหรับ Honda CBR1000RR-R SP Fireblade รายการ: แร็คท้าย+ข้าง เคชบาร์ (ถอดประกอบง่าย)', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-038', 'Honda', 'CBR500R', 'แครชบาร์', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Honda CBR500R รายการ: แครชบาร์', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-039', 'Honda', 'Cl300', 'แคชบาร์', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Honda Cl300 รายการ: แคชบาร์', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-040', 'Honda', 'Click 160', 'แก้งาน ทำสีใหม่ + แคชบาร์หน้าใหม่', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Honda Click 160 รายการ: แก้งาน ทำสีใหม่ + แคชบาร์หน้าใหม่', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-041', 'Honda', 'Click 160 abs', 'แคชบาร์', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Honda Click 160 abs รายการ: แคชบาร์', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-042', 'HONDA', 'CLICK160', 'แคชบาร์มีที่พักเท้า', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ HONDA CLICK160 รายการ: แคชบาร์มีที่พักเท้า', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-043', 'Honda', 'Click160', 'แร็คท้าย', 0, 'rear', 'งานคัสตอม KMO สำหรับ Honda Click160 รายการ: แร็คท้าย', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-044', 'Honda', 'Cluck160', 'แคชบาร์ ถ่วงน้ำหนัก เหล็ก 27 มม', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Honda Cluck160 รายการ: แคชบาร์ ถ่วงน้ำหนัก เหล็ก 27 มม', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-045', 'Honda', 'CRF Aficatwin 1100ปี2026', 'แร็คข้างใส่กล่องข้างShad38ลิตรแบบหลบท่อ', 0, 'side', 'งานคัสตอม KMO สำหรับ Honda CRF Aficatwin 1100ปี2026 รายการ: แร็คข้างใส่กล่องข้างShad38ลิตรแบบหลบท่อ', 'assets/images/rack-side.jpg', '', true, true, false),
  ('kmo-046', 'honda', 'Crf แอฟริกาทวิน1000 L', 'แคสบาร์', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ honda Crf แอฟริกาทวิน1000 L รายการ: แคสบาร์', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-047', 'Honda', 'CRF250แรลลี่่', 'แคชบาร์', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Honda CRF250แรลลี่่ รายการ: แคชบาร์', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-048', 'Honda', 'CRF300', 'แคชบาร์+แคชด้านบน ติดบัวหลัง+ย่านพับกับ+X80', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Honda CRF300 รายการ: แคชบาร์+แคชด้านบน ติดบัวหลัง+ย่านพับกับ+X80', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-049', 'Honda', 'Crf300l', 'แคชบาร์', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Honda Crf300l รายการ: แคชบาร์', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-050', 'Honda', 'Ct125', 'เชื่อมแกนพักเท้า', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Ct125 รายการ: เชื่อมแกนพักเท้า', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-051', 'Honda', 'Forza', 'แร็คข้าง 35 ลิตร', 0, 'side', 'งานคัสตอม KMO สำหรับ Honda Forza รายการ: แร็คข้าง 35 ลิตร', 'assets/images/rack-side.jpg', '', true, true, false),
  ('kmo-052', 'Honda', 'Forza 300/350', 'แคชบาร์งานคัสตอม Forza(หน้าเล็ก)', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Honda Forza 300/350 รายการ: แคชบาร์งานคัสตอม Forza(หน้าเล็ก)', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-053', 'Honda', 'Forza 750', 'Forza 750 บาร์เสริมตรงรุ่น', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Forza 750 รายการ: Forza 750 บาร์เสริมตรงรุ่น', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-054', 'Honda', 'Forza 750', 'บาร์เสริม Forza750', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Forza 750 รายการ: บาร์เสริม Forza750', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-055', 'Honda', 'Forza350', 'จอติดๆดับๆmotovision x1', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Forza350 รายการ: จอติดๆดับๆmotovision x1', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-056', 'Honda', 'Forza350', 'แคลชบาร์', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Honda Forza350 รายการ: แคลชบาร์', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-057', 'Honda', 'Forza750', 'Forza 750 บาร์เสริมตรงรุ่น', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Forza750 รายการ: Forza 750 บาร์เสริมตรงรุ่น', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-058', 'Honda', 'Forza750', 'บาร์เสริม', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Forza750 รายการ: บาร์เสริม', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-059', 'Honda', 'Forza750', 'บาร์เสริม forza750', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Forza750 รายการ: บาร์เสริม forza750', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-060', 'HONDA', 'Froza 350', 'ทำสีแครชบาร์', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ HONDA Froza 350 รายการ: ทำสีแครชบาร์', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-061', 'Honda', 'Giorno', 'ชุดแร็คท้าย แร็คข้าง', 0, 'side', 'งานคัสตอม KMO สำหรับ Honda Giorno รายการ: ชุดแร็คท้าย แร็คข้าง', 'assets/images/rack-side.jpg', '', true, true, false),
  ('kmo-062', 'Honda', 'Giorno', 'บาร์เสริม Giorno+ ใส่กับชิวแต่ง', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Giorno รายการ: บาร์เสริม Giorno+ ใส่กับชิวแต่ง', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-063', 'Honda', 'Giorno', 'บาร์เสริม Giorno+ใส่กับชิวแต่ง', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Giorno รายการ: บาร์เสริม Giorno+ใส่กับชิวแต่ง', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-064', 'Honda', 'Giorno', 'บาร์เสริม จีออโน่ *2 อัน* ใส่กับชิวครับ', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Giorno รายการ: บาร์เสริม จีออโน่ *2 อัน* ใส่กับชิวครับ', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-065', 'Honda', 'Giorno', 'บาร์เสริมใส่กับขิว', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Giorno รายการ: บาร์เสริมใส่กับขิว', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-066', 'Honda', 'Giorno', 'แคชบาร์, การ์ดแฮนด์ (เข้าไปคุยอีกที)', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Honda Giorno รายการ: แคชบาร์, การ์ดแฮนด์ (เข้าไปคุยอีกที)', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-067', 'Honda', 'Giorno+', 'บาร์เสริม Giorno+ ใส่กับชิวแต่ง', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Giorno+ รายการ: บาร์เสริม Giorno+ ใส่กับชิวแต่ง', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-068', 'Honda', 'Lead125 2026', 'แคชบาร์สั้น จับไฟสปอตส์ไลต์', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Honda Lead125 2026 รายการ: แคชบาร์สั้น จับไฟสปอตส์ไลต์', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-069', 'Honda', 'Monkey', 'แร็คติดปี๊บแบบมีถาดสไลด์', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Monkey รายการ: แร็คติดปี๊บแบบมีถาดสไลด์', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-070', 'Honda', 'NC750', 'ทำแคชบาร์ใหม่', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Honda NC750 รายการ: ทำแคชบาร์ใหม่', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-071', 'Honda', 'NX500', 'คำท้าย เอ็นเอ็ก500 แบบใหม่', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda NX500 รายการ: คำท้าย เอ็นเอ็ก500 แบบใหม่', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-072', 'Honda', 'NX500', 'ค้ำท้าย', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda NX500 รายการ: ค้ำท้าย', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-073', 'Honda', 'Nx500', 'ค้ำท้าย NX500', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Nx500 รายการ: ค้ำท้าย NX500', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-074', 'Honda', 'Nx500', 'ค้ำท้าย Nx500 แบบใหม่', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Nx500 รายการ: ค้ำท้าย Nx500 แบบใหม่', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-075', 'Honda', 'Nx500', 'ค้ำท้าย nx500 ใหม่', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Nx500 รายการ: ค้ำท้าย nx500 ใหม่', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-076', 'Honda', 'NX500', 'ค้ำท้าย แบบใหม่', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda NX500 รายการ: ค้ำท้าย แบบใหม่', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-077', 'Honda', 'Nx500', 'ค้ำท้ายแบบใหม่', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Nx500 รายการ: ค้ำท้ายแบบใหม่', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-078', 'Honda', 'Nx500', 'ค้ำท้ายใหม่', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Nx500 รายการ: ค้ำท้ายใหม่', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-079', 'Honda', 'Nx500', 'บาร์ค้ำท้าย กันแร็คหัก NX500 (แบบเก่า)', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Nx500 รายการ: บาร์ค้ำท้าย กันแร็คหัก NX500 (แบบเก่า)', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-080', 'Honda', 'Nx500', 'แบบเก่า', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Nx500 รายการ: แบบเก่า', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-081', 'Honda', 'Pcx160 2026', 'แคชบาร์ สีส้ม', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Honda Pcx160 2026 รายการ: แคชบาร์ สีส้ม', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-082', 'Honda', 'Rebel 300', 'Double seat & rear fender', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Rebel 300 รายการ: Double seat & rear fender', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-083', 'Honda', 'Rebel500', 'แร็คข้าง', 0, 'side', 'งานคัสตอม KMO สำหรับ Honda Rebel500 รายการ: แร็คข้าง', 'assets/images/rack-side.jpg', '', true, true, false),
  ('kmo-084', 'Honda', 'Super cub110', 'แร็คท้าย', 0, 'rear', 'งานคัสตอม KMO สำหรับ Honda Super cub110 รายการ: แร็คท้าย', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-085', 'Honda', 'Supercud110', 'แร็คท้าย', 0, 'rear', 'งานคัสตอม KMO สำหรับ Honda Supercud110 รายการ: แร็คท้าย', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-086', 'Honda', 'Wave 125i 2024', 'แร็คข้าง', 0, 'side', 'งานคัสตอม KMO สำหรับ Honda Wave 125i 2024 รายการ: แร็คข้าง', 'assets/images/rack-side.jpg', '', true, true, false),
  ('kmo-087', 'HONDA', 'WAVE110i', 'พักเท้าหน้าเสริม', 0, 'accessory', 'งานคัสตอม KMO สำหรับ HONDA WAVE110i รายการ: พักเท้าหน้าเสริม', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-088', 'Honda', 'X-ADV750', 'ติดตั้งจอN1Go', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda X-ADV750 รายการ: ติดตั้งจอN1Go', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-089', 'Honda', 'X-adv750', 'แฮนด์, ตุ๊กตาแฮนด์, หัวโช้ค, ก้านเบรก,ตีนเป็ด', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda X-adv750 รายการ: แฮนด์, ตุ๊กตาแฮนด์, หัวโช้ค, ก้านเบรก,ตีนเป็ด', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-090', 'Honda', 'จีออโน่', 'บาร์เสริมกระจกเดิม', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda จีออโน่ รายการ: บาร์เสริมกระจกเดิม', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-091', 'Honda', 'จีออโน่', 'บาร์เสริมติดชิว', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda จีออโน่ รายการ: บาร์เสริมติดชิว', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-092', 'Honda', 'จีออโน่', 'บาร์เสริมใส่ชิว', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda จีออโน่ รายการ: บาร์เสริมใส่ชิว', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-093', 'Honda', 'จีออโน่', 'บาร์เสริมใส่รูกระจก (รูนอกของจิ๊ก)', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda จีออโน่ รายการ: บาร์เสริมใส่รูกระจก (รูนอกของจิ๊ก)', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-094', 'Honda', 'จีออโน่', 'ใส่กับชิว (รูในจิ๊ก)', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda จีออโน่ รายการ: ใส่กับชิว (รูในจิ๊ก)', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-095', 'Honda', 'จีออโน่', 'ใส่กับชิว รูใน', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda จีออโน่ รายการ: ใส่กับชิว รูใน', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-096', 'Honda', 'ฟอซ่า 750', 'บาร์เสริม', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda ฟอซ่า 750 รายการ: บาร์เสริม', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-097', 'Honda', 'ฟอซ่า 750', 'บาร์เสริม ฟอซ่า750 แบบสั้น ตามรู้ที่ส่งให้', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda ฟอซ่า 750 รายการ: บาร์เสริม ฟอซ่า750 แบบสั้น ตามรู้ที่ส่งให้', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-098', 'Honda', 'ฟอซ่า 750', 'บาร์เสริมฟอซ่า750', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda ฟอซ่า 750 รายการ: บาร์เสริมฟอซ่า750', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-099', 'Honda', 'ฟอซ่า750', 'บาร์เสริม', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda ฟอซ่า750 รายการ: บาร์เสริม', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-100', 'Honda', 'ฟอซ่า750', 'บาร์เสริม ฟอซ่า750', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda ฟอซ่า750 รายการ: บาร์เสริม ฟอซ่า750', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-101', 'Honda', 'ฟอซ่า750', 'บาร์เสริมฟอซ่า750', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda ฟอซ่า750 รายการ: บาร์เสริมฟอซ่า750', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-102', 'Honda', 'เวฟ125i', 'ทำแร็คท้าย', 0, 'rear', 'งานคัสตอม KMO สำหรับ Honda เวฟ125i รายการ: ทำแร็คท้าย', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-103', 'Honda ADV150 ปี2020', '', 'ขึ้นแร็คข้างใหม่ สีดำ', 0, 'side', 'งานคัสตอม KMO สำหรับ Honda ADV150 ปี2020 รายการ: ขึ้นแร็คข้างใหม่ สีดำ', 'assets/images/rack-side.jpg', '', true, true, false),
  ('kmo-104', 'Honda Giorno', 'ABS 125', 'บาร์จับ', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Giorno ABS 125 รายการ: บาร์จับ', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-105', 'Honds', 'Adv160', 'แร๊คท้ายใส่จักรยานพับ', 0, 'rear', 'งานคัสตอม KMO สำหรับ Honds Adv160 รายการ: แร๊คท้ายใส่จักรยานพับ', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-106', 'Husqvarna', 'Norden 901', 'แคลชบาร์', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Husqvarna Norden 901 รายการ: แคลชบาร์', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-107', 'Kawachi KLR650 2025', '', 'แคชบาร์', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Kawachi KLR650 2025 รายการ: แคชบาร์', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-108', 'Kawasaki', 'versys 100', 'crash bars', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Kawasaki versys 100 รายการ: crash bars', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-109', 'Kawasaki', 'Versys 1000', 'Crash bars', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Kawasaki Versys 1000 รายการ: Crash bars', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-110', 'Kawasaki', 'Versys650 (ปี 24-25)', 'Versys650 แคชบาร์หน้าใหม่ (ปี 24-25)', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Kawasaki Versys650 (ปี 24-25) รายการ: Versys650 แคชบาร์หน้าใหม่ (ปี 24-25)', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-111', 'Kawasaki', 'Versys650 2017', 'แคชบ่ร์', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Kawasaki Versys650 2017 รายการ: แคชบ่ร์', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-112', 'Kawasaki', 'เวอร์ซิส 650', 'เวอร์ซิสปี 26', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Kawasaki เวอร์ซิส 650 รายการ: เวอร์ซิสปี 26', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-113', 'Kawasaki Eliminator 400/2024', '', 'เสริมตัวยึดแร็คข้าง สีดำ', 0, 'side', 'งานคัสตอม KMO สำหรับ Kawasaki Eliminator 400/2024 รายการ: เสริมตัวยึดแร็คข้าง สีดำ', 'assets/images/rack-side.jpg', '', true, true, false),
  ('kmo-114', 'Kawasaki versys650 2017', '', 'สร้างแคชบาร์(ขึ้นงานใหม่) ดัด ซ่อมแร็คท้าย', 0, 'rear', 'งานคัสตอม KMO สำหรับ Kawasaki versys650 2017 รายการ: สร้างแคชบาร์(ขึ้นงานใหม่) ดัด ซ่อมแร็คท้าย', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-115', 'KTM', '1290 ADV', 'ขึ้นแร็คท้ายใส่กระเป๋าปั้มลมLoboo', 0, 'rear', 'งานคัสตอม KMO สำหรับ KTM 1290 ADV รายการ: ขึ้นแร็คท้ายใส่กระเป๋าปั้มลมLoboo', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-116', 'Ktm 790 advปี2024', '', 'แคชบาร์บนต่อเติม, ตัดขาตั้งเดี่ยว, ขาตั้งคู่, สปอร์ตไลท์, GPS X1S, ท่อ', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Ktm 790 advปี2024 รายการ: แคชบาร์บนต่อเติม, ตัดขาตั้งเดี่ยว, ขาตั้งคู่, สปอร์ตไลท์, GPS X1S, ท่อ', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-117', 'Ktm790', '790 adventure r', 'แคชบาร์', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Ktm790 790 adventure r รายการ: แคชบาร์', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-118', 'Nmax', 'Nmax2025', 'แคชบาร์ แร็คท้าย แคชบาร์ท้าย', 0, 'rear', 'งานคัสตอม KMO สำหรับ Nmax Nmax2025 รายการ: แคชบาร์ แร็คท้าย แคชบาร์ท้าย', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-119', 'Suzuki', 'Burg man 400', 'บาร์เสริมเบิกแมน 400', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Suzuki Burg man 400 รายการ: บาร์เสริมเบิกแมน 400', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-120', 'Suzuki', 'Burgman 400', 'แคชบาร์ชุดเต็ม (อาจมีแร็คท้าย แร็คข้าง กล่อง Shad23)', 0, 'side', 'งานคัสตอม KMO สำหรับ Suzuki Burgman 400 รายการ: แคชบาร์ชุดเต็ม (อาจมีแร็คท้าย แร็คข้าง กล่อง Shad23)', 'assets/images/rack-side.jpg', '', true, true, false),
  ('kmo-121', 'Suzuki', 'Burgman400', 'บาร์เสริม เรือนไมล์', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Suzuki Burgman400 รายการ: บาร์เสริม เรือนไมล์', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-122', 'Suzuki', 'Burgman400', 'บาร์เสริมเบิกแมน', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Suzuki Burgman400 รายการ: บาร์เสริมเบิกแมน', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-123', 'Suzuki', 'Burgman400', 'บาร์เสริมเบิกแมนด่วนจี๋', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Suzuki Burgman400 รายการ: บาร์เสริมเบิกแมนด่วนจี๋', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-124', 'suzuki', 'suzuki v-strom 800 de', 'แคชบาร์', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ suzuki suzuki v-strom 800 de รายการ: แคชบาร์', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-125', 'Suzuki', 'V-Strom800DE', 'แร็คข้างท้าย', 0, 'side', 'งานคัสตอม KMO สำหรับ Suzuki V-Strom800DE รายการ: แร็คข้างท้าย', 'assets/images/rack-side.jpg', '', true, true, false),
  ('kmo-126', 'Suzuki', 'Vstrom1000', 'ซ่อมแคชบาร์', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Suzuki Vstrom1000 รายการ: ซ่อมแคชบาร์', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-127', 'suzuki', 'vstrom650', 'แรคท้าย แรคข้าง', 0, 'accessory', 'งานคัสตอม KMO สำหรับ suzuki vstrom650 รายการ: แรคท้าย แรคข้าง', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-128', 'Suzuki', 'เบิกแมน', 'บาร์เสริมบนจอ', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Suzuki เบิกแมน รายการ: บาร์เสริมบนจอ', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-129', 'Suzuki', 'เบิกแมน', 'บาร์เสริมหลังจอ', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Suzuki เบิกแมน รายการ: บาร์เสริมหลังจอ', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-130', 'Suzuki', 'เบิกแมน 400', 'บาร์เสริมบนจอ', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Suzuki เบิกแมน 400 รายการ: บาร์เสริมบนจอ', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-131', 'Suzuki', 'เบิกแมน400', 'ชุดเต็ม', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Suzuki เบิกแมน400 รายการ: ชุดเต็ม', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-132', 'Suzuki', 'เบิกแมน400', 'บาร์เสริมเรือนไมล์', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Suzuki เบิกแมน400 รายการ: บาร์เสริมเรือนไมล์', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-133', 'Suzuki GSX 8s 2022', '', 'แคชบาร์ สีฟ้า', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Suzuki GSX 8s 2022 รายการ: แคชบาร์ สีฟ้า', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-134', 'suzuki vstrom 250 sx ปี 2026', '', 'แร็คท้าย', 0, 'rear', 'งานคัสตอม KMO สำหรับ suzuki vstrom 250 sx ปี 2026 รายการ: แร็คท้าย', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-135', 'SUZUKU', 'BURGMAN400', 'เข้าไปแก้ไข บาร์เสริมกลางแฮนด์', 0, 'accessory', 'งานคัสตอม KMO สำหรับ SUZUKU BURGMAN400 รายการ: เข้าไปแก้ไข บาร์เสริมกลางแฮนด์', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-136', 'Tiger sport 660', '', 'แร็คข้างติดปี๊บ สีดำ', 0, 'side', 'งานคัสตอม KMO สำหรับ Tiger sport 660 รายการ: แร็คข้างติดปี๊บ สีดำ', 'assets/images/rack-side.jpg', '', true, true, false),
  ('kmo-137', 'Tnt 600gt / ทัวริ่ง', '', 'ซ่อมเคสบาร์/ทำสี ดำ', 0, 'service', 'งานคัสตอม KMO สำหรับ Tnt 600gt / ทัวริ่ง รายการ: ซ่อมเคสบาร์/ทำสี ดำ', 'assets/images/service.jpg', '', true, true, false),
  ('kmo-138', 'triumph', 'scrambler 1200', 'ทำแร็คข้าง แคชบาร์', 0, 'side', 'งานคัสตอม KMO สำหรับ triumph scrambler 1200 รายการ: ทำแร็คข้าง แคชบาร์', 'assets/images/rack-side.jpg', '', true, true, false),
  ('kmo-139', 'triumph', 'thruxton r 1200', 'แร็คท้าย', 0, 'rear', 'งานคัสตอม KMO สำหรับ triumph thruxton r 1200 รายการ: แร็คท้าย', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-140', 'triumph', 'trident 660', 'แคชบาร์, แร็คท้าย', 0, 'rear', 'งานคัสตอม KMO สำหรับ triumph trident 660 รายการ: แคชบาร์, แร็คท้าย', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-141', 'Triumph', 'Trident 660', 'แร็คท้าย', 0, 'rear', 'งานคัสตอม KMO สำหรับ Triumph Trident 660 รายการ: แร็คท้าย', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-142', 'Vespa', 'GTS300', 'แร็คท้าย', 0, 'rear', 'งานคัสตอม KMO สำหรับ Vespa GTS300 รายการ: แร็คท้าย', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-143', 'Vespa', 'primavera 150', 'ทำแร็คท้ายแบบสไลด์เข้าออกได้', 0, 'rear', 'งานคัสตอม KMO สำหรับ Vespa primavera 150 รายการ: ทำแร็คท้ายแบบสไลด์เข้าออกได้', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-144', 'Xsr155/ 2025', '', 'แร็คท้ายพับได้ + แร็คข้าง', 0, 'side', 'งานคัสตอม KMO สำหรับ Xsr155/ 2025 รายการ: แร็คท้ายพับได้ + แร็คข้าง', 'assets/images/rack-side.jpg', '', true, true, false),
  ('kmo-145', 'Yadea', 'GT80', 'แคชบาร์ + ไฟสปอร์ตไลท์ Future eyes X80', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Yadea GT80 รายการ: แคชบาร์ + ไฟสปอร์ตไลท์ Future eyes X80', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-146', 'Yamaha', 'Bolt r 950', 'แคชบาร์', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Yamaha Bolt r 950 รายการ: แคชบาร์', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-147', 'yamaha', 'exciter abs 2024', 'ติดตั้งแร็คข้าง กล่องข้าง และกล่องท้าย', 0, 'side', 'งานคัสตอม KMO สำหรับ yamaha exciter abs 2024 รายการ: ติดตั้งแร็คข้าง กล่องข้าง และกล่องท้าย', 'assets/images/rack-side.jpg', '', true, true, false),
  ('kmo-148', 'Yamaha', 'MT-03', 'แก้ไขจุดยึดแร็คท้าย เซอร์วิสแคชบาร์', 0, 'rear', 'งานคัสตอม KMO สำหรับ Yamaha MT-03 รายการ: แก้ไขจุดยึดแร็คท้าย เซอร์วิสแคชบาร์', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-149', 'Yamaha', 'Mt-09', 'แร็คท้าย', 0, 'rear', 'งานคัสตอม KMO สำหรับ Yamaha Mt-09 รายการ: แร็คท้าย', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-150', 'Yamaha', 'RXK', 'แร็คท้าย', 0, 'rear', 'งานคัสตอม KMO สำหรับ Yamaha RXK รายการ: แร็คท้าย', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-151', 'Yamaha', 'Tracer 9gt 2026', 'ทั้ง3อย่าง', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Yamaha Tracer 9gt 2026 รายการ: ทั้ง3อย่าง', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-152', 'Yamaha', 'Tracer900gt', 'แคชบาร์', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Yamaha Tracer900gt รายการ: แคชบาร์', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-153', 'Yamaha', 'Xmax', 'บาร์เสริมยาว ตรงรุ่น Xmax', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Yamaha Xmax รายการ: บาร์เสริมยาว ตรงรุ่น Xmax', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-154', 'Yamaha', 'Xmax', 'แคชบาร์ v1', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Yamaha Xmax รายการ: แคชบาร์ v1', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-155', 'Yamaha', 'Xmax', 'แคชบาร์ Xmax V.2', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Yamaha Xmax รายการ: แคชบาร์ Xmax V.2', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-156', 'Yamaha', 'Xmax', 'แคชบาร์หน้างอ', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Yamaha Xmax รายการ: แคชบาร์หน้างอ', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-157', 'Yamaha', 'Xmax300', 'เอ็กแม็ก วี1', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Yamaha Xmax300 รายการ: เอ็กแม็ก วี1', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-158', 'Yamaha', 'Xmax300', 'แร็คข้าง', 0, 'side', 'งานคัสตอม KMO สำหรับ Yamaha Xmax300 รายการ: แร็คข้าง', 'assets/images/rack-side.jpg', '', true, true, false),
  ('kmo-159', 'Yamaha', 'Xsr900', 'บาร์เสริมสำหรับติด จอgps', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Yamaha Xsr900 รายการ: บาร์เสริมสำหรับติด จอgps', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-160', 'Yamaha', 'เอ็กแม็ก300', 'v1', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Yamaha เอ็กแม็ก300 รายการ: v1', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-161', 'ZONGSHEN', 'Cyclone mini panda', 'แร็คท้าย', 0, 'rear', 'งานคัสตอม KMO สำหรับ ZONGSHEN Cyclone mini panda รายการ: แร็คท้าย', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-162', 'Zontes', '350E', 'บังท่อ', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Zontes 350E รายการ: บังท่อ', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-163', 'Zontes', '350E', 'แคชบาร์', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Zontes 350E รายการ: แคชบาร์', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-164', 'Zontes', '350E', 'แร็คท้าย,แร็คข้าง', 0, 'side', 'งานคัสตอม KMO สำหรับ Zontes 350E รายการ: แร็คท้าย,แร็คข้าง', 'assets/images/rack-side.jpg', '', true, true, false),
  ('kmo-165', 'Zontes', '368d', 'เเคชบาร์หน้า', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Zontes 368d รายการ: เเคชบาร์หน้า', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-166', 'Zontes', '368G', 'n1go 2610+บาร์เสริม 690+ปลั๊ก 250', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Zontes 368G รายการ: n1go 2610+บาร์เสริม 690+ปลั๊ก 250', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-167', 'Zontes', '368G', 'ดัดแครชบาร์', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Zontes 368G รายการ: ดัดแครชบาร์', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-168', 'zontes', '368g', 'แร็คข้าง', 0, 'side', 'งานคัสตอม KMO สำหรับ zontes 368g รายการ: แร็คข้าง', 'assets/images/rack-side.jpg', '', true, true, false),
  ('kmo-169', 'Zontes', '368g', 'แร็คทัาย + แร็คข้าง', 0, 'side', 'งานคัสตอม KMO สำหรับ Zontes 368g รายการ: แร็คทัาย + แร็คข้าง', 'assets/images/rack-side.jpg', '', true, true, false),
  ('kmo-170', 'Zontes 368G V2 2026', 'Zontes 368G V2 2026', 'เเร็คท้าย เเร็คข้าง ตัวค้ำโช๊คเเร็คท้าย', 0, 'rear', 'งานคัสตอม KMO สำหรับ Zontes 368G V2 2026 Zontes 368G V2 2026 รายการ: เเร็คท้าย เเร็คข้าง ตัวค้ำโช๊คเเร็คท้าย', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-171', 'Zontes368G', '', 'ที่ค้ำแร็คหลัง /สีเหมือนบาร์ด้านหน้า', 0, 'rear', 'งานคัสตอม KMO สำหรับ Zontes368G รายการ: ที่ค้ำแร็คหลัง /สีเหมือนบาร์ด้านหน้า', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-172', 'คาวาซากิ', 'คาวาซากิKLR650', 'แคชบาร์หน้า', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ คาวาซากิ คาวาซากิKLR650 รายการ: แคชบาร์หน้า', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-173', 'อื่นๆ', 'ซอนเทส368จี', 'ดำ', 0, 'accessory', 'งานคัสตอม KMO สำหรับ อื่นๆ ซอนเทส368จี รายการ: ดำ', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-174', 'อื่นๆ', 'ซอนเทส368จี', 'ปี๊บ 38', 0, 'accessory', 'งานคัสตอม KMO สำหรับ อื่นๆ ซอนเทส368จี รายการ: ปี๊บ 38', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-175', 'เวฟ125x ปี2007', '', 'ค้ำแร็คท้าย', 0, 'rear', 'งานคัสตอม KMO สำหรับ เวฟ125x ปี2007 รายการ: ค้ำแร็คท้าย', 'assets/images/rack-rear-adv.jpg', '', true, true, false),
  ('kmo-other-001', 'Honda', 'ADV 350', 'แคชบาร์ท้าย ADV 350', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Honda ADV 350 รายการ: แคชบาร์ท้าย ADV 350', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-other-002', 'Honda', 'ADV 350', 'แคชบาร์ท้าย ADV350 ดำเงา', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Honda ADV 350 รายการ: แคชบาร์ท้าย ADV350 ดำเงา', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-other-003', 'Honda', 'ADV350', 'อื่นๆ (จอ Motovision x1s )', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda ADV350 รายการ: อื่นๆ (จอ Motovision x1s )', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-other-004', 'Honda', 'ADV350', 'แคชบาร์หน้า + แคชบาร์ท้าย ADV350', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Honda ADV350 รายการ: แคชบาร์หน้า + แคชบาร์ท้าย ADV350', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-other-005', 'Honda', 'Adv350', 'น็อตชิว', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Adv350 รายการ: น็อตชิว', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-other-006', 'Honda', 'Adv350', 'แคชบาร์ท้าย', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Honda Adv350 รายการ: แคชบาร์ท้าย', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-other-007', 'Honda', 'Adv350', 'แคชบาร์ท้ายเอดีวี350', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Honda Adv350 รายการ: แคชบาร์ท้ายเอดีวี350', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-other-008', 'Honda', 'CRF 300R', 'พักเท้าcrf', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda CRF 300R รายการ: พักเท้าcrf', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-other-009', 'Honda', 'CRF300', 'พักเท้าCRF', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda CRF300 รายการ: พักเท้าCRF', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-other-010', 'Honda', 'CRF300RALLY', 'อื่นๆ (กระเป๋าหลัง Shad tr50)', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda CRF300RALLY รายการ: อื่นๆ (กระเป๋าหลัง Shad tr50)', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-other-011', 'Honda', 'Crf300rally', 'อื่นๆ (พักเท้าคนซ้อน)', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Crf300rally รายการ: อื่นๆ (พักเท้าคนซ้อน)', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-other-012', 'Honda', 'Lead125', 'อื่นๆ (พักเท้าหน้า)', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda Lead125 รายการ: อื่นๆ (พักเท้าหน้า)', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-other-013', 'Honda', 'NX500', 'อื่นๆ (คำท้าย NX500 แบบใหม่)', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda NX500 รายการ: อื่นๆ (คำท้าย NX500 แบบใหม่)', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-other-014', 'Honda', 'WAVE125R', 'อื่นๆ (ชิวหน้าพร้อมบาร์ยึด)', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda WAVE125R รายการ: อื่นๆ (ชิวหน้าพร้อมบาร์ยึด)', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-other-015', 'Honda', 'adv350', 'อื่นๆ (แคชบาร์ 4 ชุด)', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Honda adv350 รายการ: อื่นๆ (แคชบาร์ 4 ชุด)', 'assets/images/crashbar.jpg', '', true, true, false),
  ('kmo-other-016', 'Honda', 'cb650r อีครัช 2024', 'อื่นๆ (ปิ๊บหลัง 55 F2Moto สีดำ)', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda cb650r อีครัช 2024 รายการ: อื่นๆ (ปิ๊บหลัง 55 F2Moto สีดำ)', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-other-017', 'Honda', 'wave 125 2023', 'อื่นๆ (ชิวหน้า)', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda wave 125 2023 รายการ: อื่นๆ (ชิวหน้า)', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-other-018', 'Honda', 'จีออโน่', 'พักเท้าจีออโน่', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda จีออโน่ รายการ: พักเท้าจีออโน่', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-other-019', 'Honda', 'จีออโน่', 'พักเท้าหน้า 1 ชุด', 0, 'accessory', 'งานคัสตอม KMO สำหรับ Honda จีออโน่ รายการ: พักเท้าหน้า 1 ชุด', 'assets/images/spotlight.jpg', '', true, true, false),
  ('kmo-other-020', 'Honda', 'ฟอซ่า 350', 'แคชบาร์ข้าง! ฟอซ่า', 0, 'crashbar', 'งานคัสตอม KMO สำหรับ Honda ฟอซ่า 350 รายการ: แคชบาร์ข้าง! ฟอซ่า', 'assets/images/crashbar.jpg', '', true, true, false)
on conflict (id) do update set
  brand = excluded.brand,
  model = excluded.model,
  name = excluded.name,
  price = excluded.price,
  category = excluded.category,
  description = excluded.description,
  image_url = excluded.image_url,
  shopee_url = excluded.shopee_url,
  allow_booking = excluded.allow_booking,
  allow_order = excluded.allow_order,
  featured = excluded.featured;
