// OpenNext custom Worker: keep the generated Next.js fetch handler and add reminder scheduling.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore .open-next/worker.js is generated by the OpenNext Cloudflare build.
import handler from './.open-next/worker.js';

type BookingWorkerEnv = CloudflareEnv & {
  NOTIFICATION_DISPATCH_SECRET?: string;
  NEXT_PUBLIC_BOOKING_SITE_URL?: string;
};

type WorkerExecutionContext = {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
};

const worker = {
  fetch: handler.fetch,

  async scheduled(_controller: unknown, env: BookingWorkerEnv, ctx: WorkerExecutionContext) {
    const secret = env.NOTIFICATION_DISPATCH_SECRET;
    if (!secret) throw new Error('NOTIFICATION_DISPATCH_SECRET is not configured');

    const origin = env.NEXT_PUBLIC_BOOKING_SITE_URL;
    if (!origin) throw new Error('NEXT_PUBLIC_BOOKING_SITE_URL is not configured');
    const request = new Request(new URL('/api/notifications/dispatch', origin), {
      method: 'POST',
      headers: { Authorization: `Bearer ${secret}` },
    });
    const response = await handler.fetch(request, env, ctx);
    if (!response.ok) {
      throw new Error(`Scheduled notification dispatch failed with HTTP ${response.status}`);
    }
  },
};

export default worker;

